### ISSUE TITLE
XML dependency problem: AbstractMethodError: org.apache.xerces.dom.DocumentImpl.getXmlStandalone()Z

### ISSUE THREAD

**Issue by victorzinho** [gvtools/gvtools#2]
I'm getting this exception some time after interacting for the first time with gvtools.

```
Exception in thread "Timer-0" java.lang.AbstractMethodError: org.apache.xerces.dom.DocumentImpl.getXmlStandalone()Z
    at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.setDocumentInfo(DOM2TO.java:377)
    at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:131)
    at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:98)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:683)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:727)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:340)
    at java.util.prefs.XmlSupport.writeDoc(XmlSupport.java:276)
    at java.util.prefs.XmlSupport.exportMap(XmlSupport.java:355)
    at java.util.prefs.FileSystemPreferences$7.run(FileSystemPreferences.java:622)
    at java.util.prefs.FileSystemPreferences$7.run(FileSystemPreferences.java:615)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.util.prefs.FileSystemPreferences.writeBackCache(FileSystemPreferences.java:614)
    at java.util.prefs.FileSystemPreferences.syncSpiPrivileged(FileSystemPreferences.java:801)
    at java.util.prefs.FileSystemPreferences.access$2300(FileSystemPreferences.java:50)
    at java.util.prefs.FileSystemPreferences$12.run(FileSystemPreferences.java:771)
    at java.util.prefs.FileSystemPreferences$12.run(FileSystemPreferences.java:769)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.util.prefs.FileSystemPreferences.syncSpi(FileSystemPreferences.java:768)
    at java.util.prefs.AbstractPreferences.sync2(AbstractPreferences.java:1332)
    at java.util.prefs.AbstractPreferences.sync2(AbstractPreferences.java:1337)
    at java.util.prefs.AbstractPreferences.sync(AbstractPreferences.java:1323)
    at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:747)
    at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
    at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
    at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
    at java.util.prefs.FileSystemPreferences$3.run(FileSystemPreferences.java:432)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

**Comment by jaymmodi** [comment]
I resolved this error by updating the version of xercesImpl dependency in pom.

Thanks.
